//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add comment.
        /// </summary>
        internal static string addCommLabel {
            get {
                return ResourceManager.GetString("addCommLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string btBack {
            get {
                return ResourceManager.GetString("btBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Posts.
        /// </summary>
        internal static string btFirstPosts {
            get {
                return ResourceManager.GetString("btFirstPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More Posts.
        /// </summary>
        internal static string btMorePosts {
            get {
                return ResourceManager.GetString("btMorePosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NEXT.
        /// </summary>
        internal static string btNext {
            get {
                return ResourceManager.GetString("btNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PREVIOUS.
        /// </summary>
        internal static string btPrevious {
            get {
                return ResourceManager.GetString("btPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See Post.
        /// </summary>
        internal static string btSeePosts {
            get {
                return ResourceManager.GetString("btSeePosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show image details.
        /// </summary>
        internal static string detailsLabel {
            get {
                return ResourceManager.GetString("detailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not more post.
        /// </summary>
        internal static string lblNotMorePost {
            get {
                return ResourceManager.GetString("lblNotMorePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mandatory Field.
        /// </summary>
        internal static string mandatoryField {
            get {
                return ResourceManager.GetString("mandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No posts found.
        /// </summary>
        internal static string noPostsFound {
            get {
                return ResourceManager.GetString("noPostsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string searchButton {
            get {
                return ResourceManager.GetString("searchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search for posts.
        /// </summary>
        internal static string searchLabel {
            get {
                return ResourceManager.GetString("searchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show comments.
        /// </summary>
        internal static string showCommsLabel {
            get {
                return ResourceManager.GetString("showCommsLabel", resourceCulture);
            }
        }
    }
}
